import "./globals.css";
import { Gothic_A1, Montserrat } from "next/font/google";

const gothic = Gothic_A1({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-gothic",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Travel Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
